services:
  pgsql:
    container_name: pgsql
    image: postgres:latest
    volumes: 
      - ./backend/src/main/resources/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=abdouldiallo
      - POSTGRES_DB=abdouldiallo
    ports:
      - "5432:5432"

  server:
    container_name: server
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    depends_on:
      - pgsql
  
  